fix: Actions

diff --git a/.github/workflows/run-notify.yml b/.github/workflows/run-notify.yml
--- a/.github/workflows/run-notify.yml
+++ b/.github/workflows/run-notify.yml
@@ -38,9 +38,9 @@ jobs:
         run: |
           git config user.name "github-actions[bot]"
           git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
-          git add .
+          git add src/data/* 
           if ! git diff --staged --quiet; then
-            git commit -m "Update CSVs by workflow ${GITHUB_RUN_ID}" || echo "commit failed (no changes)"
+            git commit -m "Update Notify History by workflow ${GITHUB_RUN_ID}" || echo "commit failed (no changes)"
             git push
           else
             echo "No changes to commit"
